### PR TITLE
fix(project-search): replace autocomplete-search with search and context-menu

### PR DESCRIPTION
**Pull request by WANZARGEN**
### To Reviewers
- [ ] Skip (`style`, `chore` ONLY)
- [ ] Not that difficult

### Type of Change
- [ ] New feature
- [x] Bug fixes
- [ ] Feature improvement
- [ ] Refactor
- [ ] Others (performance improvement, refactoring, CI/CD, etc.)

### Checklist
- [x] `Error / Warning / Lint / Type`

### Description

- Fix not more button not working issue
- Fix hiding menu after select menu issue

### CODE REVIEW

**Review by minseolee — APPROVED** [review]
Nice work!!!!!
I've checkout on your branch, and checked it works well.

I would remind you to not forget to downgrade mirinae version (`^1.1.0-beta.457`) after cherry pick

**Comment by sulmoJ** [comment]
Really fast!! I also finished double-checking the 457 version of Mirinae!
Thank you for your hard work!

**Review by sulmoJ — APPROVED** [review]
Really fast!! I also finished double-checking the 457 version of Mirinae!
Thank you for your hard work!

**Review by yuda110 — APPROVED** [review]
LGTM!
Finally every autocomplete-search is removed except one 🥹

**Pull request merged**
