### PR TITLE
feat(relocate-dashboard): create relocate-dashboard markup & link to local storage

### PR DESCRIPTION
**Pull request by piggggggggy**
### To Reviewers
- [ ] Skip (`style`, `chore`, `ci` ONLY)
- [ ] Not that difficult

### Type of Change
- [ ] New feature
- [ ] Bug fixes
- [x] Feature improvement
- [ ] Refactor
- [ ] Others (performance improvement, CI/CD, etc.)

### Affects to
- [ ] Packages
  - [ ] core-lib
  - [ ] mirinae
  - [ ] etc 

- [ ] Apps
  - [ ] storybook
  - [x] web

### Checklist
- Did you check the `lint` and `type`?
- Did you document the changes?
  - Changes in `mirinae` should be reflected in `storybook`.
- Did you test the app after the package changes?

### Description

SSIA

image

### CODE REVIEW

**Review by yuda110 — APPROVED** [review]
😮 You created whole new modal!

**Review by WANZARGEN — COMMENTED** [review]
Please solve the problem for preview build~ and let me check!

**Comment by WANZARGEN** [comment]
issue: I checked it at preview, and there is an error below 😮, and learn more guide doesn't appear.

image
image

**Review by WANZARGEN — CHANGES_REQUESTED** [review]
I left an issue that looks critical 😵

**Comment by WANZARGEN** [comment]
issue: there are several errors when clicking 'Don't show me again' and 'Dismiss' buttons.

**Review by WANZARGEN — APPROVED** [review]
LGTM~

**Pull request merged**
